In [2]:
import numpy as np

In [7]:
# NumPy 실습문제 1: ndarray 생성과 인덱싱 기초

data = [
    [87, 90, 85],
    [92, 88, 79],
    [76, 95, 90],
    [88, 84, 92]
]
student = ["철수", "영희", "민수", "수진"]

arr = np.array(data)

print(f"영희의 성적은 {arr[student.index("영희")]}")
print("=" * 20)
print(f"학생들의 수학 성적은 {arr[:, 1]}")
print("=" * 20)
sub = [k in ["철수", "수진"] for k in student]
print(f"철수와 수진의 영어 점수 {arr[sub, 2]}")

영희의 성적은 [92 88 79]
학생들의 수학 성적은 [90 88 95 84]
철수와 수진의 영어 점수 [85 92]


In [11]:
# NumPy 실습문제 2: 슬라이싱과 브로드캐스팅
arr = np.arange(1, 13).reshape(3, 4)
print(arr[:, -1])
print("=" * 20)
print(arr + [[0], [10], [0]])
print("=" * 20)
print(arr[:, 2:4])

[ 4  8 12]
[[ 1  2  3  4]
 [15 16 17 18]
 [ 9 10 11 12]]
[[ 3  4]
 [ 7  8]
 [11 12]]


In [3]:
# NumPy 실습문제 3: 조건 인덱싱 + 통계 연산
np.random.seed(0)
scores = np.random.randint(0, 101, size=100)

over90 = (scores >= 90).sum()
mean_under_50 = np.mean(scores * (scores < 50))
total_mean = np.mean(scores)
total_max = np.max(scores)
total_min = np.min(scores)

print(f"90점 이상인 학생의 수: {over90}")
print(f"50점 미만 점수의 평균: {mean_under_50:.2f}")
print(f"전체 학생의 평균:{total_mean:.2f}, 최대:{total_max}, 최소:{total_min}")

90점 이상인 학생의 수: 5
50점 미만 점수의 평균: 12.87
전체 학생의 평균:48.75, 최대:100, 최소:0


In [10]:
# NumPy 실습문제 4: 다차원 배열 연산 및 axis 활용
data = np.array([
    [23, 25, 22],  # Day 1
    [24, 26, 23],
    [22, 24, 21],
    [25, 27, 24],
    [23, 25, 22]
])

print(f"각 센서의 5일간의 평균: {np.sum(data, axis=0) / 5}")
print(f"각 날짜별 평균: {(np.sum(data, axis=1) / 3).round(2)}")
print(f"전체 데이터의 최대:{np.max(data)}, 최소:{np.min(data)}")

각 센서의 5일간의 평균: [23.4 25.4 22.4]
각 날짜별 평균: [23.33 24.33 22.33 25.33 23.33]
전체 데이터의 최대:27, 최소:21


In [13]:
# NumPy 실습문제 5: 행렬 곱과 브로드캐스팅
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[1, 0], [0, 1], [1, 1]])

mul = A @ B
print(mul)
print("="*20)
mul = mul + np.array([10, 100])
print(mul)
print("="*20)
print(np.shape(mul))

[[ 4  5]
 [10 11]]
[[ 14 105]
 [ 20 111]]
(2, 2)
